name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: tf-pwa-op
        python-version: 3.11
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Install dependencies
      run: |
        conda install cmake tensorflow cuda-minimal-build
    - name: build so file
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..
    - name: build whl
      run: |
        python setup.py bdist_wheel
