name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.10, 3.12]
    defaults:
      run:
        shell: bash -el {0}   # start bash with conda
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: tf-pwa-op
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda install tensorflow cuda-minimal-build
    - name: set gpu link to build without gpu
      run: |
        mkdir -p third_party/gpus/cuda/
        ln -s $(dirname `which python`)/../targets/x86_64-linux/include third_party/gpus/cuda/include
    - name: build so file
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..
    - name: build whl
      run: |
        python setup.py bdist_wheel
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.whl
